### ISSUE TITLE
cloud.7cav update

### ISSUE THREAD

**Issue by SyniRon** [7Cav/syp_proj#1]

**Comment by SyniRon** [comment]
Current version: 28.0.1
New version: 28.0.6

Downtime message sent

**Comment by SyniRon** [comment]
Attempted to complete but received errors pulling the new image. Doesn't seem to be an issue on our end seems to be on the docker registry end, so will just try again another day.

**Comment by astetchkov** [comment]
can we shoot to re-attempt in the near future?

**Comment by SyniRon** [comment]
closing as nextcloud was shut down
